text:
  - changed-files:
      - any-glob-to-any-file: src/content/**/*.md

code:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*.js
          - src/**/*.ts
          - src/**/*.tsx
          - src/**/*.html
          - src/**/*.css
          - src/**/*.astro
